[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

upload_port = /dev/cu.usbserial-1130
monitor_port = /dev/cu.usbserial-1130

lib_deps =
    chris--a/Keypad@^3.1.1
    marcoschwartz/LiquidCrystal_I2C@^1.1.4

monitor_speed = 9600
